jc_commande_liste:
    path:      /commande/liste/{page}
    defaults:  { _controller: JCCommandeBundle:Commande:liste, page:html }
    requirements:
        page:    ([0-9]+)
    
jc_commande_detail:
    path:      /commande/detail/{id}
    defaults:  { _controller: JCCommandeBundle:Commande:detail }
    requirements:
        id:    ([0-9]+)
    options:
        expose: true


jc_commande_creation:
    path:      /commande/creation
    defaults:  { _controller: JCCommandeBundle:Commande:creation }
 

jc_commande_modification:
    path:      /commande/modification/{id}
    defaults:  { _controller: JCCommandeBundle:Commande:modification }
    requirements:
        id:    ([0-9]+)
    options:
        expose: true


      
        
jc_commande_pdf_facture:
    path:     /commande/pdf/{idCommande}/{envoyer}
    defaults: { _controller: JCCommandeBundle:Commande:genererPDFFacture }
  
  
  
  
jc_commande_supprimer_paiement_facture:
    path:     /commande/supprimerPaiement
    defaults: { _controller: JCCommandeBundle:Commande:supprimerPaiementFacture }  
    options:
        expose: true





#Route pour action ajax
jc_commande_get_tva:
    path:	/commande/get_tva
    defaults:  { _controller: JCCommandeBundle:Commande:getTVA }
    options:
        expose: true


jc_commande_change_etat:
    path:	/commande/changeEtat
    defaults:  { _controller: JCCommandeBundle:Commande:changeEtat }
    options:
        expose: true


jc_commande_paiement_commande:
    path:	/commande/paiementCommande
    defaults:  { _controller: JCCommandeBundle:Commande:paiementCommande }
    options:
        expose: true

