jc_accueil_homepage:
    path:     /{annee}
    defaults: { _controller: JCAccueilBundle:Accueil:index , annee: html}


jc_accueil_recherche:
    path:     /recherche/
    defaults: { _controller: JCAccueilBundle:Accueil:recherche }
