jc_facturation_homepage:
    path:     /facturation/{annee}
    defaults: { _controller: JCFacturationBundle:Facturation:index, annee: html }
    requirements:
        annee:    ([0-9]+)

jc_facturation_calcul:
    path:     /facturation/calcul/{nomCollectivite}/{annee}
    defaults: { _controller: JCFacturationBundle:Facturation:calcul }
    requirements:
        annee:    ([0-9]+)
        
        
        
        
jc_facturation_pdf_facture:
    path:     /facturation/pdf/{nomCollectivite}/{annee}
    defaults: { _controller: JCFacturationBundle:Facturation:genererPDFFacture }
    requirements:
        annee:    ([0-9]+)