<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends EntityRepository
{
	
	public function getActiviteOrdreAlpha() {
    return $this
      ->createQueryBuilder('a')
      ->orderBy('a.nom', 'ASC')
    ;
    
    }
    
    
    public function queryFindAll() {
    return $this
      ->createQueryBuilder('a')
    ;
    
    }

}
