<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
	public function getApplicationOrdreAlpha() {
    return $this
      ->createQueryBuilder('a')
      ->orderBy('a.nom', 'ASC')
    ;
    
    }
    
    
    
    
    public function getApplicationWithActiviteName($name) {

    	
		return $this
		    ->createQueryBuilder('a')
		    ->leftJoin('a.activite', 'act')
		    -> where('act.nom = :name')
			->setParameter('name', $name)
		  ;

		//On filtre
		//$qb->where($qb->expr()->in('act.name', $name));

		}
		 
    
    
}
