<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CleRepartitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CleRepartitionRepository extends EntityRepository
{
	
	public function getCleOrdreAlpha() {
    return $this
      ->createQueryBuilder('cr')
      ->orderBy('cr.nom', 'ASC')
    ;
    
    }
    
}
