<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollectiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectiviteRepository extends EntityRepository
{

	public function findAllNom(){
		
		return $this
		->createQueryBuilder('c')
		->select('c.nom')
		->orderBy('c.nom', 'ASC')
		->getQuery()	
		->getResult()
		;
	}
        
        
        public function findAllOrdreAlpha(){
		
		return $this
		->createQueryBuilder('c')
		->orderBy('c.nom', 'ASC')
		->getQuery()	
		->getResult()
		;
	}
	
	
	
	
	public function findCollectivitesMutualiseesDansAnnee($annee){
		
	
			
			
			
		return $this
			->getEntityManager()
		    ->getRepository('JCCommandeBundle:Collectivite')
			
			->createQueryBuilder('c')
	        ->leftJoin('JCCommandeBundle:InformationCollectivite', 'ic', 'WITH', 'ic.collectivite = c')
	       
	        ->where('year(c.dateDebutMutualisation) <= :annee AND year(c.dateFinMutualisation) >= :annee')
	        ->setParameter('annee', $annee)

   			->getQuery()
			->getResult();
		
	}

}
