<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollectiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectiviteRepository extends EntityRepository
{

	public function findAllNom(){
		
		return $this
		->createQueryBuilder('c')
		->select('c.nom')
		->orderBy('c.nom', 'ASC')
		->getQuery()	
		->getResult()
		;
	}
        
        
        public function findAllOrdreAlpha(){
		
		return $this
		->createQueryBuilder('c')
		->orderBy('c.nom', 'ASC')
		->getQuery()	
		->getResult()
		;
	}

}
