<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollectiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectiviteRepository extends EntityRepository
{

	public function findAllNom(){
		
		return $this
		->createQueryBuilder('c')
		->select('c.nom')
		->orderBy('c.nom', 'ASC')
		->getQuery()	
		->getResult()
		;
	}
        
        
        public function findAllOrdreAlpha(){
		
		return $this
		->createQueryBuilder('c')
		->orderBy('c.nom', 'ASC')
		->getQuery()	
		->getResult()
		;
	}
	
	
	
	public function findCollectivitesPourAnnee($annee){
		
		return $this
		->createQueryBuilder('c')

		->where('year(c.dateDebutMutualisation) <= :annee AND year(c.dateFinMutualisation) >= :annee')
	  	->setParameter('annee', $annee)
		  	
	  	//On trie par collectivite et par clé 
	  	->add('orderBy', 'c.id ASC')
   			
  		->getQuery()
		->getResult();

		;
	}
	
	
	
	
	public function findCollectivitesPourDateOrdreAlpha($date){
		
		return $this
		->createQueryBuilder('c')

		->where('c.dateDebutMutualisation <= :date AND c.dateFinMutualisation >= :date')
	  	->setParameter('date', $date)
		  	
	  	//On trie par collectivite et par clé 
	  	->add('orderBy', 'c.nom ASC')
   			
  		->getQuery()
		->getResult();

		;
	}
	
	
	
	}
