<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
	

	public function findCommandePourCollectiviteAvecStatutPourAnnee($collectivite, $statut, $annee){
		
		return $this
			->getEntityManager()
		    ->getRepository('JCCommandeBundle:CommandeConcerneCollectivite')
			
			->createQueryBuilder('ccc')
			
			->leftJoin('ccc.commande','com')
			->addSelect('com')
			
			->leftJoin('com.etats', 'passeEtat')
			->addSelect('passeEtat')
			
			->leftJoin('passeEtat.etat', 'et')
			->addSelect('et')
			
			->where('ccc.collectivite = :collectivite AND et.libelle = :statut AND passeEtat.datePassage > :annee AND passeEtat.datePassage < :annee2')
			->setParameter('collectivite',$collectivite)
			->setParameter('statut',$statut)
			->setParameter('annee',$annee)
			->setParameter('annee2',strval($annee+1))
	
			->getQuery()	
			->getResult();

	}

	
}
