<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeConcerneCollectiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeConcerneCollectiviteRepository extends EntityRepository
{
	
	

	
	
	
	/*
	*	Recherche des CommandeConcerneCollectivite avec l'id d'une commande	
	*/
	public function findCommandeConcerneCollectiviteAvecCommande($id) {
		
	    $qb = $this->createQueryBuilder('ccc');

		$qb ->where('ccc.commande = :id')
			->setParameter('id', $id)
		;

		return $qb ->getQuery()
					->getResult()
		;
		
	}
        
    /*
	*	Recherche des CommandeConcerneCollectivite avec l'id d'une commande et de la collectivite	
	*/
        public function findCommandeConcerneCollectiviteAvecCommandeEtCollectivite($idCommande, $idCollectivite) {
		
	    $qb = $this->createQueryBuilder('ccc');

		$qb ->where('ccc.commande = :idCommande')
			->setParameter('idCommande', $idCommande) 
            ->andWhere('ccc.collectivite = :idCollectivite')
			->setParameter('idCollectivite', $idCollectivite)
		;

		return $qb ->getQuery()
		->getResult()
		;
		
	}
	
	
	
	/*
	*	Recherche des CommandeConcerneCollectivite avec l'id de la collectivite, l'année
	*/
        /*public function findCommandeConcerneCollectiviteAvecCommandeEtCollectivite($idCommande, $idCollectivite) {
		
	    $qb = $this->createQueryBuilder('ccc');

		$qb ->where('ccc.commande = :idCommande')
			->setParameter('idCommande', $idCommande) 
            ->andWhere('ccc.collectivite = :idCollectivite')
			->setParameter('idCollectivite', $idCollectivite)
		;

		return $qb ->getQuery()
		->getResult()
		;
		
	}*/
	
}
