<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
	
	public function findByStatu($statu){
		
		return $this
		->createQueryBuilder('c')
		->where('c.etat = :statu')
		->setParameter('statu', $statu)
		->getQuery()	
		->getResult()

		;
	}


	public function findByStatuEtAnnee($statu, $annee){
		
		return $this
		->createQueryBuilder('c')
		->where('c.etat = :statu')
		->setParameter('statu', $statu)
		->andWhere('c.annee = :annee')
		->setParameter('annee', $annee)
		->getQuery()	
		->getResult()

		;
	}




	public function findCommandesAvecAnnee($annee){
		
		return $this
		->createQueryBuilder('c')
		->where('c.dateCreation = :annee')
		->setParameter('annee', $anne)
		->getQuery()	
		->getResult()

		;

	}

	
}
