<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandePasseEtatRepository extends EntityRepository
{	
	
	public function findDernierEtatCommande($commande){
		
		return $this
		->createQueryBuilder('cpe')
		->where('cpe.commande = :commande')
		->setParameter('commande', $commande)
		->orderBy('cpe.datePassage', 'DESC')
		->setMaxResults(1)
		->getQuery()	
		->getResult()

		;
	}

	public function findEtatPourCommande($commande, $etat){
		
		return $this
		->createQueryBuilder('cpe')
		->where('cpe.commande = :commande')
		->setParameter('commande', $commande)
		->andWhere('cpe.etat = :etat')
		->setParameter('etat', $em->getRepository('JCCommandeBundle:Etat')->findEtatPourCommande($etat))
		->setMaxResults(1)
		->getQuery()	
		->getResult()

		;
	}

	

}
