<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandePasseEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandePasseEtatRepository extends EntityRepository
{
	
	public function findDernierEtatCommande($commande){
		
		return $this
		->createQueryBuilder('cpe')
		->where('cpe.commande = :commande')
		->setParameter('commande', $commande)
		->orderBy('cpe.datePassage', 'DESC')
		->setMaxResults(1)
		->getQuery()	
		->getResult()

		;
	}

	public function findEtatPourCommande($commande, $etat){
		
		return $this
		->createQueryBuilder('cpe')
	    ->leftJoin('cpe.etat', 'e')
	    -> where('e.libelle = :etat')
		->setParameter('etat', $etat)
		->andWhere('cpe.commande = :commande')
		->setParameter('commande', $commande)		
		->setMaxResults(1)
		->getQuery()	
		->getResult()

		;
	}



public function findPasseEtatDansLannee($etat, $annee) {

	    return $qb = $this
	    	->createQueryBuilder('cpe')
			->leftJoin('cpe.etat','ec')
			->where('ec.libelle = :etat')
			->setParameter('etat', $etat) 
            ->andWhere('cpe.datePassage > :annee')
			->setParameter('annee', $annee)
			->getQuery()
	    	->getResult()
	    	;
	}
	
	
}
