<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandePasseEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandePasseEtatRepository extends EntityRepository
{
	
	public function findDernierEtatCommande($commande){
		
		return $this
		->createQueryBuilder('cpe')
		->where('cpe.commande = :commande')
		->setParameter('commande', $commande)
		->orderBy('cpe.datePassage', 'DESC')
		->setMaxResults(1)
		->getQuery()	
		->getResult()

		;
	}

	public function findEtatPourCommande($commande, $etat){
		
		return $this
		->createQueryBuilder('cpe')
	    ->leftJoin('cpe.etat', 'e')
	    -> where('e.libelle = :etat')
		->setParameter('etat', $etat)
		->andWhere('cpe.commande = :commande')
		->setParameter('commande', $commande)		
		->setMaxResults(1)
		->getQuery()	
		->getResult()

		;
	}



public function findPasseEtatDansEntreDates($etat, $dateDebut, $dateFin) {

	    return $qb = $this
	    	->createQueryBuilder('cpe')
			->leftJoin('cpe.etat','ec')
			->where('ec.libelle = :etat')
			->setParameter('etat', $etat)
			 
            ->andWhere('cpe.datePassage >= :dateDebut')
           	->setParameter('dateDebut', $dateDebut)
           	
            ->andWhere('cpe.datePassage < :dateFin')
			->setParameter('dateFin', $dateFin)
			
			->getQuery()
	    	->getResult()
	    	;
	}
	
	
	
	
	public function findPasseEtatDansAnnee($etat, $annee) {

	    return $qb = $this
	    	->createQueryBuilder('cpe')
			->addSelect('COUNT(cpe.id) AS nombre')
			
			->leftJoin('cpe.etat','ec')
			->where('ec.libelle = :etat')
			->setParameter('etat', $etat)
			
			->leftJoin('cpe.commande','com')
			->addSelect('com')
		
			 
            ->andWhere('year(cpe.datePassage) = :annee')
           	->setParameter('annee', $annee)

			->groupBy('com.id')
			
			->getQuery()
	    	->getResult()
	    	;
	}

	
}
