<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformationCollectiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationCollectiviteRepository extends EntityRepository
{
	
	public function findInfoPourCollectivitePourCleEtAnnee($collectivite, $cle, $annee){
		
		return $qb = $this
	    	->createQueryBuilder('ic')
			->where('ic.collectivite = :collectivite')
			->setParameter('collectivite', $collectivite)
			 
            ->andWhere('ic.cleRepartition > :cleRepartition')
           	->setParameter('cleRepartition', $cleRepartition)
           	
           	->andWhere('ic.annee = :annee')
           	->setParameter('annee', $annee)
			
			->getQuery()
	    	->getResult()
	    	;
	}
	
	
	
	
	public function findToutesInfosPourCollectiviteEtAnnee($collectivite, $annee){
		
		return $qb = $this
	    	->createQueryBuilder('ic')
			->where('ic.collectivite = :collectivite')
			->setParameter('collectivite', $collectivite)
           	
           	->andWhere('ic.annee = :annee')
           	->setParameter('annee', $annee)
			
			->getQuery()
	    	->getResult()
	    	;
	}
	
	
	//On pourrai récupérer l'année dans commande..
	public function findSommeDeCleEtAnneePourCommande($cle, $annee, $commande){
		
		
		return $this
			->getEntityManager()
		    ->getRepository('JCCommandeBundle:CommandeConcerneCollectivite')
			
			->createQueryBuilder('ccc')
	        ->select('SUM(ic.nombre)')
	        ->leftJoin('JCCommandeBundle:InformationCollectivite', 'ic', 'WITH', 'ic.collectivite = ccc.collectivite')
	       
	        ->where('ccc.commande = :commande AND ic.cleRepartition =:cle')
	        ->setParameter('commande', $commande)
	        ->setParameter('cle', $commande->getActivite()->getCleRepartition())

   			->getQuery()
	    	->getSingleResult();
		
		
			}
	
	
	
	
	
	/*
	*	Recherche toutes les informations des collectivites mutualisée à une année donnée
	*/
	public function findInformationsPourAnnee($annee) {
		
		
		return $this
			
			->createQueryBuilder('ic')
			->leftJoin('JCCommandeBundle:Collectivite', 'c', 'WITH', 'c = ic.collectivite')

			->where('year(c.dateDebutMutualisation) <= :annee AND year(c.dateFinMutualisation) >= :annee AND ic.annee = :annee')
		  	->setParameter('annee', $annee)
		  	
		  	//On trie par collectivite et par clé 
		  	->add('orderBy', 'c.id ASC', 'ic.cleRepartition ASC')
   			
   			->getQuery()
			->getResult();
		
	}
		
	
	
}
