<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformationCollectiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationCollectiviteRepository extends EntityRepository
{
	
	public function findInfoPourCollectivitePourCleEtAnnee($collectivite, $cle, $annee){
		
		return $qb = $this
	    	->createQueryBuilder('ic')
			->where('ic.collectivite = :collectivite')
			->setParameter('collectivite', $collectivite)
			 
            ->andWhere('ic.cleRepartition > :cleRepartition')
           	->setParameter('cleRepartition', $cleRepartition)
           	
           	->andWhere('ic.annee = :annee')
           	->setParameter('annee', $annee)
			
			->getQuery()
	    	->getResult()
	    	;
	}
	
	
	
	
	public function findToutesInfosPourCollectiviteEtAnnee($collectivite, $annee){
		
		return $qb = $this
	    	->createQueryBuilder('ic')
			->where('ic.collectivite = :collectivite')
			->setParameter('collectivite', $collectivite)
           	
           	->andWhere('ic.annee = :annee')
           	->setParameter('annee', $annee)
			
			->getQuery()
	    	->getResult()
	    	;
	}
	
	
	
	public function findSommeDeCleEtAnnee($cle, $annee){
		
		return $qb = $this
	    	->createQueryBuilder('ic')
	    	->select('SUM(ic.nombre)')
	    	
			->andWhere('ic.cleRepartition = :cle')
           	->setParameter('cle', $cle)
           	
           	->andWhere('ic.annee = :annee')
           	->setParameter('annee', $annee)
			
			->getQuery()
	    	->getSingleResult()
	    	;
	}
	
	
	
	
	
	
}
