<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends EntityRepository
{
	public function findLivraisonsOrdreAlpha() {
            return $this
              ->createQueryBuilder('l')
              ->orderBy('l.nom', 'ASC')
              ->orderBy('l.adresse', 'ASC')
              ->getQuery()	
              ->getResult()
        ;
    
    }

}
