<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TempsPasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempsPasseRepository extends EntityRepository
{
	
	public function findOneAvecAnneeEtActivitePourCollectivite($annee, $activite, $collectivite){
		
		return $this
			->createQueryBuilder('tp')
	
			->where('tp.annee = :annee AND tp.activite = :activite AND tp.collectivite = :collectivite')
			->setParameter('annee',$annee)
			->setParameter('activite',$activite)
			->setParameter('collectivite',$collectivite)
			->setMaxResults(1)
	
			->getQuery()	
			->getResult();
	}
}
