<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TVARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVARepository extends EntityRepository
{
	
	public function getTVACroissant() {
	    return $this
	      ->createQueryBuilder('t')
	      ->orderBy('t.pourcentage', 'ASC')
	    ;
    
    }
}
