<?php

namespace JC\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
	
	public function getUtilisateurOrdreAlpha() {
    return $this
      ->createQueryBuilder('u')
      ->orderBy('u.nom', 'ASC')
      ->orderBy('u.prenom', 'ASC')

    ;
  }
	
	
	
}
